spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nov2024
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#spring.datasource.url=jdbc:mysql://localhost:3306/nov2024
#spring.datasource.username=root
#spring.datasource.password=password
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

env: PRODUCTION-SERVER